name: Prune untagged images
inputs:
  container: customaction
  prune-age: 15
  dry-run: true
on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  prune:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: |
            .github/workflows/prune_images.yaml
      - name: Install requests
        run: pip install requests
      - name: Prune untagged images
        env:
          GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python ghcr-prune.py