name: Prune images

inputs:
  container:
    description: 'Container name'
    required: true
  prune-age:
    description: 'Prune age in hours'
    default: 1
    required: true
  dry-run:
    description: 'Dry run (true/false)'
    required: true
  github-token:
    description: 'GH_TOKEN to use GitHub API'
    required: true
 

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install requests
      shell: bash
      run: pip install requests
    - name: Prune untagged images
      shell: bash
      run: python .github/actions/delete_docker_img/ghcr-prune.py
       